name: ci

on: [push, pull_request]

jobs:
  test_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build rc shell
      run: make
    - name: Run rc tests
      run: make check
    - name: Run integration tests
      run: ./test-integration.sh
    - name: Test demo script
      run: ./demo-integration.sh
    # run: run-test-bestline  (disabled, needs work)

